login/urls.py
from django.urls import path

from . import views
app_name='login'
urlpatterns = [
    path('', views.index, name='index'),
    path('test',views.test,name='test'),
    path('select',views.select,name='select'),
    path('result',views.result,name='result')
]

xuanke/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models
from django.db import models


class Student(models.Model):
    stuName= models.CharField(max_length=5)
    stuClass = models.CharField(max_length=10)
    stuNum = models.IntegerField()
    stuPasswd = models.CharField(max_length=256)
    stuCou = models.TextField(default='')
    def __str__(self):
        return self.stuName


class Course(models.Model):
    couName = models.CharField(max_length=10)
    couTea = models.CharField(max_length=5)
    couId = models.IntegerField(default=0)
    couTime = models.CharField(max_length=30)

    couAllNum = models.IntegerField(default=0)
    couLeftNum = models.IntegerField(default=0)

    couPer = models.TextField(default='')

    def __str__(self):
        return self.couName
# Create your models here.

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Student,Course
student = Student()

def index(request):
    return render(request, 'login/login.html')

# Create your views here.
def test(request):
    return HttpResponse("Hello, test")

def select(request):

    course = Course.objects.all()
    context = {'course': course}

    if request.method == 'POST':
        user = request.POST.get('username')
        pw = request.POST.get('password')

    student = Student.objects.get(stuName=user)
    context['student']=student

    if student.stuPasswd==pw:
        return render(request, 'login/select.html', context)
    else:
        return render(request, 'login/wrong.html',{'wrong':'your password is wrong'})

def result(request):
    if request.method == "POST":

        wrongtext ={"wrong":''}
        stu = request.POST.get('stu')
        student=Student.objects.get(stuName=stu)
        print(student)
        couSel_list = request.POST.getlist('couSel')
        for i in couSel_list:
            course = Course.objects.get(couName=i)
            if course.couLeftNum==0:
                wrongtext["wrong"]+=course.couName+"已满"
            if course.couName in student.stuCou:
                wrongtext["wrong"] += course.couName + "已选"
            else:
                course.couAllNum+=1
                course.couLeftNum-=1
                if course.couPer:
                    course.couPer +=student.stuName
                else:
                    course.couPer+=','+student.stuName
                if student.stuCou:
                    student.stuCou += ',' + course.couName
                else:
                    student.stuCou+=course.couName
        print(wrongtext)
        if wrongtext["wrong"]:
            return render(request,'login/wrong.html',wrongtext)
        print (student.stuCou)
        stuCou_list = student.stuCou.split(',')
        student.save()
        course.save()
        return render(request, 'login/result.html',{'stuCou_list':stuCou_list,'student':student})

login/templates/login/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body style="background-image: url({% static 'login/images/2.jpg' %});background-size:100% 200%;background-repeat:no-repeat;">
     <div style="margin: 15% 40%;">
        <h1>login</h1>
       <form action="{% url 'login:select' %}" method="post">

            <p>
                <label for="id_username">用户名：</label>
                <input type="text" id="id_username" name="username" placeholder="用户名" autofocus required />
            </p>

            <p>
                <label for="id_password">密&nbsp;&nbsp;&nbsp;码：</label>
                <input type="password" id="id_password" placeholder="密码" name="password" required >
            </p>
            <input type="submit" value="确定">
        </form>
    </div>
</body>
</html>

login/templates/login/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>result</title>
</head>
<body>
<div style="text-align:center;">
<h1>{{student.stuName}} 已选课程</h1>
{% for i in stuCou_list %}
    <p>
        {{i}}
    </p>
{% endfor %}

</div>
</body>
</html>

login/templates/login/select.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>选课</title>
</head>
<body style="background-image: url({% static 'login/images/3.jpg' %});background-size:100% 200%;background-repeat:no-repeat;">
     <div style="text-align:center;">
         <font color="white">
        <h1>选课</h1>
        <h2>hello {{student.stuName}}</h2>
        <form action="{% url 'login:result' %}" method="post">
          <h3>已选课程:{{student.stuCou}}</h3>
          {% if course %}
            <p>
              课程名称 时间 老师 已选 可选
            </p>
            {% for q in course %}
              <p>
              <input type="checkbox" name="couSel" value="{{q.couName}}">
              {{ q.couName }} {{q.couTime}} {{q.couTea}} {{q.couAllNum}} {{q.couLeftNum}}
              </p>
            {% endfor %}

          {% else %}
            <p>No polls are available.</p>
          {% endif %}
          <input type="hidden" name="stu" value={{student.stuName}}>
          <input type="submit" value="提交">
        </form>
         </font>
    </div>
</body>
</html>

login/templates/login/wrong.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>wrong</title>
</head>
<body>
<div style="text-align:center;">
  <h2>warning</h2>
<h3>{{wrong}}</h3>
</div>
</body>
</html>